
const fs = require('fs');
const path = require('path');

const DOMAINS = ['example.com', 'blog.dev', 'shop.store', 'portfolio.io'];
const PATHS = ['/', '/about', '/contact', '/products/1', '/products/2', '/blog/hello-world', '/blog/tutorial'];
const COUNTRIES = ['US', 'GB', 'CN', 'DE', 'JP', 'FR', 'IN', 'BR', 'CA', 'AU'];
const REFERRERS = [
    '', // Direct
    'https://www.google.com/',
    'https://www.bing.com/',
    'https://twitter.com/',
    'https://github.com/',
    'https://news.ycombinator.com/'
];
const USER_AGENTS = [
    // Windows Chrome
    'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
    // Windows Edge
    'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36 Edg/120.0.0.0',
    // Mac Safari
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.2 Safari/605.1.15',
    // Linux Firefox (Tux icon)
    'Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/115.0',
    // Android Chrome
    'Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Mobile Safari/537.36',
    // iOS Safari
    'Mozilla/5.0 (iPhone; CPU iPhone OS 17_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Mobile/15E148 Safari/604.1'
];

function randomChoice(arr) {
    return arr[Math.floor(Math.random() * arr.length)];
}

function randomDate(start, end) {
    return new Date(start.getTime() + Math.random() * (end.getTime() - start.getTime()));
}

function generateSQL() {
    const records = [];
    const endDate = new Date();
    const startDate = new Date();
    startDate.setDate(startDate.getDate() - 90); // Last 90 days for better trend visualization

    const output = [];
    output.push('-- Seed data generated by scripts/generate_seed.js');
    output.push('DELETE FROM visits;'); // Clear existing data
    
    // Generate pool of sessions for realistic UV (some repeat, some new)
    const sessions = [];
    for(let i=0; i<100; i++) {
        sessions.push(Math.random().toString(36).substring(2, 15));
    }

    // Generate 1000 visits
    for (let i = 0; i < 1000; i++) {
        const domain = randomChoice(DOMAINS);
        const url = `https://${domain}${randomChoice(PATHS)}`;
        const referrer = randomChoice(REFERRERS);
        const userAgent = randomChoice(USER_AGENTS);
        const ip = `192.168.${Math.floor(Math.random()*255)}.${Math.floor(Math.random()*255)}`;
        const country = randomChoice(COUNTRIES);
        const timestamp = randomDate(startDate, endDate).toISOString();
        
        // Randomize PV/UV ratio based on domain stickiness
        let baseReuse = 0.6; // Default
        if (domain === 'example.com') baseReuse = 0.85; // High engagement
        else if (domain === 'blog.dev') baseReuse = 0.3; // Low engagement (many one-time visitors)
        else if (domain === 'shop.store') baseReuse = 0.6; // Moderate

        const reuseChance = Math.max(0, Math.min(1, baseReuse + (Math.random() * 0.2 - 0.1))); // +/- 10% variance, clamped 0-1
        
        let sessionId;
        if (Math.random() < reuseChance && sessions.length > 0) {
            sessionId = randomChoice(sessions);
        } else {
            sessionId = Math.random().toString(36).substring(2, 15);
            sessions.push(sessionId); // Add to pool
        }

        // Escape single quotes if necessary (simple version)
        const safeUa = userAgent.replace(/'/g, "''");
        const safeRef = referrer.replace(/'/g, "''");

        output.push(`INSERT INTO visits (url, referrer, user_agent, ip, country, domain, session_id, timestamp) VALUES ('${url}', '${safeRef}', '${safeUa}', '${ip}', '${country}', '${domain}', '${sessionId}', '${timestamp}');`);
    }

    fs.writeFileSync(path.join(__dirname, '../seed.sql'), output.join('\n'));
    console.log('Generated seed.sql with ' + output.length + ' lines.');
}

generateSQL();
