import { D1Database } from '@cloudflare/workers-types';

/**
 * Interface representing the Cloudflare Worker Environment Bindings.
 * These correspond to the variables defined in wrangler.toml or the Cloudflare Dashboard.
 */
export type Bindings = {
  DB: D1Database;
  API_KEY?: string;
  ALLOWED_ORIGINS?: string;
  SITE_NAME?: string;
  AUTHOR_NAME?: string;
  TZ_OFFSET?: string; // e.g. "8", "-5"
  IGNORE_IPS?: string; // comma separated
  IGNORE_PATHS?: string; // comma separated
};

/**
 * Payload expected from the client-side tracker.
 */
export interface CollectPayload {
  url: string;
  referrer?: string;
  sessionId?: string;
  width?: number;
  language?: string;
}

/**
 * Internal representation of a visit record as stored in the database.
 */
export interface VisitRecord {
  url: string;
  referrer: string;
  user_agent: string;
  ip: string;
  country: string;
  domain: string;
  session_id: string;
  timestamp?: string; // Optional as it is auto-generated by DB
}

export interface StatsSummary {
  pv: number;
  uv: number;
  bounceRate: number;
  todayPv: number;
  todayUv: number;
}

export interface KeyValueStat {
  key: string;
  count: number;
}

export interface ChartData {
  time: string;
  pv: number;
  uv: number;
}

export interface DashboardStats {
  summary: StatsSummary;
  topPages: KeyValueStat[];
  topReferrers: KeyValueStat[];
  topCountries: KeyValueStat[];
  topOS: KeyValueStat[];
  topBrowsers: KeyValueStat[];
  chartData: ChartData[];
  domains?: string[];
}
